// <auto-generated />
using System;
using GuildDashboard.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GuildDashboard.Server.Migrations
{
    [DbContext(typeof(GuildDashboardDbContext))]
    [Migration("20260321114806_AddFrontierProfiles")]
    partial class AddFrontierProfiles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GuildDashboard.Server.Models.ControlledSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuildId")
                        .HasColumnType("int");

                    b.Property<decimal?>("InfluenceDelta24h")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InfluencePercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsClean")
                        .HasColumnType("bit");

                    b.Property<bool>("IsControlled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsExpansionCandidate")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFromSeed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHeadquarter")
                        .HasColumnType("bit");

                    b.Property<bool>("IsThreatened")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.ToTable("ControlledSystems", (string)null);
                });

            modelBuilder.Entity("GuildDashboard.Server.Models.EddnRawMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("GatewayTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("MessageJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SchemaRef")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SourceSoftware")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceUploader")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SystemName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ReceivedAt");

                    b.HasIndex("SchemaRef");

                    b.ToTable("EddnRawMessages", (string)null);
                });

            modelBuilder.Entity("GuildDashboard.Server.Models.FrontierProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CommanderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrontierCustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("GuildId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastFetchedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastSystemName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShipName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SquadronName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FrontierCustomerId")
                        .IsUnique();

                    b.HasIndex("GuildId");

                    b.ToTable("FrontierProfiles", (string)null);
                });

            modelBuilder.Entity("GuildDashboard.Server.Models.Guild", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FactionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InaraFactionId")
                        .HasColumnType("int");

                    b.Property<int?>("InaraSquadronId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SquadronName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Guilds", (string)null);
                });

            modelBuilder.Entity("GuildDashboard.Server.Models.GuildSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GuildId")
                        .HasColumnType("int");

                    b.Property<decimal>("InfluencePercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsClean")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.ToTable("GuildSystems", (string)null);
                });

            modelBuilder.Entity("GuildDashboard.Server.Models.SquadronMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommanderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("GuildId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.HasIndex("GuildId", "CommanderName")
                        .IsUnique();

                    b.ToTable("SquadronMembers", (string)null);
                });

            modelBuilder.Entity("GuildDashboard.Server.Models.SquadronSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GuildId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MembersCount")
                        .HasColumnType("int");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.ToTable("SquadronSnapshots", (string)null);
                });

            modelBuilder.Entity("GuildDashboard.Server.Models.FrontierProfile", b =>
                {
                    b.HasOne("GuildDashboard.Server.Models.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId");

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("GuildDashboard.Server.Models.SquadronMember", b =>
                {
                    b.HasOne("GuildDashboard.Server.Models.Guild", "Guild")
                        .WithMany("SquadronMembers")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("GuildDashboard.Server.Models.SquadronSnapshot", b =>
                {
                    b.HasOne("GuildDashboard.Server.Models.Guild", "Guild")
                        .WithMany("SquadronSnapshots")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("GuildDashboard.Server.Models.Guild", b =>
                {
                    b.Navigation("SquadronMembers");

                    b.Navigation("SquadronSnapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
