// <auto-generated />
using System;
using GuildDashboard.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GuildDashboard.Server.Migrations
{
    [DbContext(typeof(GuildDashboardDbContext))]
    partial class GuildDashboardDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GuildDashboard.Server.Models.ControlledSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuildId")
                        .HasColumnType("int");

                    b.Property<decimal?>("InfluenceDelta72h")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InfluencePercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsClean")
                        .HasColumnType("bit");

                    b.Property<bool>("IsControlled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsExpansionCandidate")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFromSeed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHeadquarter")
                        .HasColumnType("bit");

                    b.Property<bool>("IsThreatened")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUnderSurveillance")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.ToTable("ControlledSystems", (string)null);
                });

            modelBuilder.Entity("GuildDashboard.Server.Models.DeclaredChantier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CmdrName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ConstructionResourcesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DeclaredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuildId")
                        .HasColumnType("int");

                    b.Property<string>("MarketId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("StationNameKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("SystemNameKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.HasIndex("GuildId", "MarketId")
                        .IsUnique()
                        .HasFilter("[MarketId] IS NOT NULL");

                    b.HasIndex("GuildId", "SystemNameKey", "StationNameKey")
                        .IsUnique()
                        .HasFilter("[MarketId] IS NULL");

                    b.ToTable("DeclaredChantiers", (string)null);
                });

            modelBuilder.Entity("GuildDashboard.Server.Models.FrontierOAuthSession", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("AccessTokenExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("AccessTokenProtected")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastRefreshAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RefreshTokenProtected")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Scope")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TokenType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("FrontierOAuthSessions", (string)null);
                });

            modelBuilder.Entity("GuildDashboard.Server.Models.FrontierProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CommanderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrontierCustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("GuildId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastFetchedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastSystemName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShipName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SquadronName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FrontierCustomerId")
                        .IsUnique();

                    b.HasIndex("GuildId");

                    b.ToTable("FrontierProfiles", (string)null);
                });

            modelBuilder.Entity("GuildDashboard.Server.Models.FrontierUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CommanderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("GuildId")
                        .HasColumnType("int");

                    b.Property<string>("SquadronName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.HasIndex("GuildId");

                    b.ToTable("FrontierUsers", (string)null);
                });

            modelBuilder.Entity("GuildDashboard.Server.Models.Guild", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FactionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InaraCmdrUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InaraFactionId")
                        .HasColumnType("int");

                    b.Property<string>("InaraFactionPresenceUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InaraSquadronId")
                        .HasColumnType("int");

                    b.Property<string>("InaraSquadronUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastAvatarImportAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastSystemsImportAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SquadronName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Guilds", (string)null);
                });

            modelBuilder.Entity("GuildDashboard.Server.Models.GuildSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Allegiance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("CoordsX")
                        .HasColumnType("float");

                    b.Property<double?>("CoordsY")
                        .HasColumnType("float");

                    b.Property<double?>("CoordsZ")
                        .HasColumnType("float");

                    b.Property<int>("FactionCount")
                        .HasColumnType("int");

                    b.Property<string>("Government")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GuildId")
                        .HasColumnType("int");

                    b.Property<string>("InaraUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("InfluencePercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsClean")
                        .HasColumnType("bit");

                    b.Property<string>("LastUpdatedText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("Population")
                        .HasColumnType("bigint");

                    b.Property<string>("Power")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryStarClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StationCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.HasIndex("GuildId", "Name")
                        .IsUnique();

                    b.ToTable("GuildSystems", (string)null);
                });

            modelBuilder.Entity("GuildDashboard.Server.Models.SquadronMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommanderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("GuildId")
                        .HasColumnType("int");

                    b.Property<string>("InaraUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.HasIndex("GuildId", "CommanderName")
                        .IsUnique();

                    b.ToTable("SquadronMembers", (string)null);
                });

            modelBuilder.Entity("GuildDashboard.Server.Models.SquadronSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GuildId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MembersCount")
                        .HasColumnType("int");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.ToTable("SquadronSnapshots", (string)null);
                });

            modelBuilder.Entity("GuildDashboard.Server.Models.DeclaredChantier", b =>
                {
                    b.HasOne("GuildDashboard.Server.Models.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("GuildDashboard.Server.Models.FrontierProfile", b =>
                {
                    b.HasOne("GuildDashboard.Server.Models.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId");

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("GuildDashboard.Server.Models.FrontierUser", b =>
                {
                    b.HasOne("GuildDashboard.Server.Models.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId");

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("GuildDashboard.Server.Models.SquadronMember", b =>
                {
                    b.HasOne("GuildDashboard.Server.Models.Guild", "Guild")
                        .WithMany("SquadronMembers")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("GuildDashboard.Server.Models.SquadronSnapshot", b =>
                {
                    b.HasOne("GuildDashboard.Server.Models.Guild", "Guild")
                        .WithMany("SquadronSnapshots")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("GuildDashboard.Server.Models.Guild", b =>
                {
                    b.Navigation("SquadronMembers");

                    b.Navigation("SquadronSnapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
