// <auto-generated />
using System;
using GuildDashboard.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GuildDashboard.Server.Migrations
{
    [DbContext(typeof(GuildDashboardDbContext))]
    [Migration("20260320225000_AddSquadronSnapshotAndRole")]
    partial class AddSquadronSnapshotAndRole
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GuildDashboard.Server.Models.Guild", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("DisplayName").HasColumnType("nvarchar(max)");
                    b.Property<string>("FactionName").HasColumnType("nvarchar(max)");
                    b.Property<int?>("InaraFactionId").HasColumnType("int");
                    b.Property<int?>("InaraSquadronId").HasColumnType("int");
                    b.Property<string>("Name").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("SquadronName").HasColumnType("nvarchar(max)");
                    b.HasKey("Id");
                    b.ToTable("Guilds", (string)null);
                });

            modelBuilder.Entity("GuildDashboard.Server.Models.SquadronMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("AvatarUrl").HasColumnType("nvarchar(max)");
                    b.Property<string>("CommanderName").IsRequired().HasColumnType("nvarchar(450)");
                    b.Property<int>("GuildId").HasColumnType("int");
                    b.Property<DateTime?>("LastSyncedAt").HasColumnType("datetime2");
                    b.Property<string>("Role").HasColumnType("nvarchar(max)");
                    b.HasKey("Id");
                    b.HasIndex("GuildId");
                    b.HasIndex("GuildId", "CommanderName").IsUnique();
                    b.ToTable("SquadronMembers", (string)null);
                });

            modelBuilder.Entity("GuildDashboard.Server.Models.SquadronSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<int>("GuildId").HasColumnType("int");
                    b.Property<DateTime>("LastSyncedAt").HasColumnType("datetime2");
                    b.Property<int?>("MembersCount").HasColumnType("int");
                    b.Property<bool>("Success").HasColumnType("bit");
                    b.HasKey("Id");
                    b.HasIndex("GuildId");
                    b.ToTable("SquadronSnapshots", (string)null);
                });

            modelBuilder.Entity("GuildDashboard.Server.Models.SquadronMember", b =>
                {
                    b.HasOne("GuildDashboard.Server.Models.Guild", "Guild")
                        .WithMany("SquadronMembers")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Guild");
                });

            modelBuilder.Entity("GuildDashboard.Server.Models.SquadronSnapshot", b =>
                {
                    b.HasOne("GuildDashboard.Server.Models.Guild", "Guild")
                        .WithMany("SquadronSnapshots")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Guild");
                });

            modelBuilder.Entity("GuildDashboard.Server.Models.Guild", b =>
                {
                    b.Navigation("SquadronMembers");
                    b.Navigation("SquadronSnapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
